'use client'

export {
  LiveUpdatesContext,
  LiveUpdatesProvider,
  OptimizationAnalyticsRoot,
  OptimizationContext,
  OptimizationProvider,
  OptimizationRoot,
  OptimizedEntry,
  prefetchManagedEntries,
  useCanOptimizeState,
  useConsentState,
  useEntryResolver,
  useEventStreamState,
  useLiveUpdates,
  useMergeTagResolver,
  useOptimization,
  useOptimizationActions,
  useOptimizationContext,
  useOptimizedEntry,
  useProfileState,
  useSelectedOptimizationsState,
} from '@contentful/optimization-react-web'
export type {
  AutoPageEmissionContext,
  AutoPagePayload,
  AutoPagePayloadOptions,
  AutoPageRouteState,
  ContentfulOptimizationOrNull,
  InitialAutoPageEvent,
  LiveUpdatesContextValue,
  LiveUpdatesProviderProps,
  ManagedEntryDescriptor,
  ManagedEntryHandoff,
  ManagedEntryPrefetchRuntime,
  OnStatesReady,
  OptimizationAnalyticsRootProps,
  OptimizationContextValue,
  OptimizationProviderProps,
  OptimizationRootProps,
  OptimizationSdk,
  OptimizationWebRuntime,
  OptimizedEntryErrorFallback,
  OptimizedEntryLoadingFallback,
  OptimizedEntryProps,
  OptimizedEntryRenderContext,
  TrackEntryInteractionOptions,
  UseEntryResolverResult,
  UseMergeTagResolverResult,
  UseOptimizationActionsResult,
  UseOptimizedEntryParams,
  UseOptimizedEntryResult,
} from '@contentful/optimization-react-web'
