bodyFormat: "{body}\n\n\n[[{ticket_id}](https://contentful.atlassian.net/browse/{ticket_id})]"
headerFormat: '{emoji} {type}({scope}): {subject}'
skipScope: false
ticketIdQuestion: 'Enter the JIRA ID'
