packages:
  - implementations/*
  - lib/*
  - platforms/javascript/*
  - platforms/javascript/web-frameworks/*
  - universal/*

catalog:
  '@contentful/rich-text-html-renderer': ^17.1.6
  '@contentful/rich-text-types': ^17.2.5
  '@microsoft/api-extractor': ^7.56.0
  '@playwright/test': ^1.57.0
  '@preact/signals-core': ^1.12.1
  '@rslib/core': ^0.19.4
  '@types/express': ^5.0.3
  '@types/node': ^24.0.13
  '@types/qs': ^6.14.0
  '@types/supertest': ^6.0.3
  '@vitest/coverage-v8': ^3.2.4
  browserslist: ^4.25.1
  diary: ^0.4.5
  contentful: ^11.10.2
  dotenv: ^17.2.2
  es-toolkit: ^1.39.10
  express: ^5.1.0
  express-rate-limit: ^8.1.0
  happy-dom: ^20.0.2
  msw: ^2.10.5
  p-retry: ^7.1.0
  pm2: ^6.0.13
  qs: ^6.14.0
  rimraf: ^6.0.1
  rollup-plugin-visualizer: ^6.0.3
  supertest: ^7.1.3
  tslib: ^2.8.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  vite: ^7.1.11
  vitest: ^3.2.4
  vite-bundle-analyzer: ^1.2.1
  vite-plugin-resolve-umd-format: ^1.0.0
  vite-tsconfig-paths: ^5.1.4
  zod: ^4.1.5

engineStrict: true

nodeVersion: 20.19.5

onlyBuiltDependencies:
  - contentful-cli
  - core-js
  - detox
  - dtrace-provider
  - esbuild
  - msw
  - spawn-sync
  - unrs-resolver

overrides:
  '@playwright/test': 'catalog:'
  '@types/node': 'catalog:'
  typescript: 'catalog:'
  vitest: 'catalog:'

useNodeVersion: 22.17.0
