packages:
  - implementations/*
  - lib/*
  - platforms/javascript/*
  - universal/*

catalog:
  '@playwright/test': ^1.55.1
  '@preact/signals-core': ^1.12.1
  '@types/express': ^5.0.3
  '@types/node': ^24.0.13
  '@types/supertest': ^6.0.3
  '@vitest/coverage-v8': ^3.2.4
  browserslist: ^4.25.1
  contentful: ^11.7.19
  dotenv: ^17.2.2
  es-toolkit: ^1.39.10
  express: ^5.1.0
  express-rate-limit: ^8.1.0
  msw: ^2.10.5
  p-retry: ^7.1.0
  pm2: ^6.0.13
  rimraf: ^6.0.1
  rollup: ^4.44.1
  supertest: 7.1.3
  tslib: ^2.8.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  vitest: ^3.2.4
  zod: ^4.1.5

engineStrict: true

nodeVersion: 20.19.5

onlyBuiltDependencies:
  - contentful-cli
  - core-js
  - detox
  - dtrace-provider
  - esbuild
  - msw
  - spawn-sync
  - unrs-resolver

overrides:
  '@playwright/test': 'catalog:'
  '@types/node': 'catalog:'
  typescript: 'catalog:'
  vitest: 'catalog:'

useNodeVersion: 22.17.0
