packages:
  - implementations/*
  - platforms/javascript/*

catalog:
  '@playwright/test': ^1.54.0
  '@types/node': ^24.0.13
  '@vitest/coverage-v8': ^3.2.4
  browserslist: ^4.25.1
  rimraf: ^6.0.1
  rollup: ^4.44.1
  tslib: ^2.8.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  vitest: ^3.2.4

engineStrict: true

nodeVersion: 16.20.0

onlyBuiltDependencies:
  - esbuild
  - msw

overrides:
  '@playwright/test': 'catalog:'
  '@types/node': 'catalog:'
  typescript: 'catalog:'
  vitest: 'catalog:'

useNodeVersion: 22.17.0
