packages:
  - lib/*
  - implementations/*
  - platforms/javascript/*

catalog:
  '@playwright/test': ^1.55.1
  '@preact/signals-core': ^1.12.1
  '@types/node': ^24.0.13
  '@vitest/coverage-v8': ^3.2.4
  browserslist: ^4.25.1
  contentful: ^11.7.19
  dotenv: ^17.2.2
  es-toolkit: ^1.39.10
  msw: ^2.10.5
  p-retry: ^7.1.0
  pm2: ^6.0.13
  rimraf: ^6.0.1
  rollup: ^4.44.1
  tslib: ^2.8.1
  tsx: ^4.20.3
  typescript: ^5.8.3
  vitest: ^3.2.4
  zod: ^4.1.5

engineStrict: true

nodeVersion: 16.20.0

onlyBuiltDependencies:
  - contentful-cli
  - esbuild
  - msw
  - spawn-sync

overrides:
  '@playwright/test': 'catalog:'
  '@types/node': 'catalog:'
  typescript: 'catalog:'
  vitest: 'catalog:'

useNodeVersion: 22.17.0
