'use client'

export {
  LiveUpdatesContext,
  LiveUpdatesProvider,
  OptimizationAnalyticsRoot,
  OptimizationContext,
  OptimizationProvider,
  OptimizationRoot,
  OptimizedEntry,
  prefetchManagedEntries,
  useCanOptimizeState,
  useConsentState,
  useEntryResolver,
  useEventStreamState,
  useLiveUpdates,
  useMergeTagResolver,
  useOptimization,
  useOptimizationActions,
  useOptimizationContext,
  useOptimizedEntry,
  useProfileState,
  useSelectedOptimizationsState,
} from './index'
export type {
  AnalyticsOptimizationHandoff,
  AutoPageEmissionContext,
  AutoPagePayload,
  AutoPagePayloadOptions,
  AutoPageRouteState,
  BrowserOptimizationHandoff,
  ContentOptimizationHandoff,
  ContentOptimizationHydrationMode,
  ContentfulOptimizationOrNull,
  InitialAutoPageEvent,
  LiveUpdatesContextValue,
  LiveUpdatesProviderProps,
  ManagedEntryDescriptor,
  ManagedEntryHandoff,
  ManagedEntryPrefetchRuntime,
  OnStatesReady,
  OptimizationAnalyticsRootProps,
  OptimizationContextValue,
  OptimizationHydrationMode,
  OptimizationProviderConfigProps,
  OptimizationProviderProps,
  OptimizationRootProps,
  OptimizationSdk,
  OptimizationWebRuntime,
  OptimizedEntryBaselineProps,
  OptimizedEntryErrorFallback,
  OptimizedEntryLoadingFallback,
  OptimizedEntryManagedProps,
  OptimizedEntryProps,
  OptimizedEntryRenderContext,
  OptimizedEntryRenderProp,
  TrackEntryInteractionOptions,
  UseEntryResolverResult,
  UseMergeTagResolverResult,
  UseOptimizationActionsResult,
  UseOptimizedEntryBaselineParams,
  UseOptimizedEntryManagedParams,
  UseOptimizedEntryParams,
  UseOptimizedEntryResult,
} from './index'
export {
  NextAppAutoPageTracker,
  type NextAppAutoPageContext,
  type NextAppAutoPageTrackerProps,
} from './router/next-app'
