/* eslint-disable no-console -- CLI */

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const GENERATED_FILENAME = 'contentful-generated.d.ts'
const SCRIPT_DIRECTORY = path.dirname(fileURLToPath(import.meta.url))
const MOCKS_DIRECTORY = path.resolve(SCRIPT_DIRECTORY, '..')
const SPACE_EXPORT_PATH = path.join(
  MOCKS_DIRECTORY,
  'src/contentful/data/space/ctfl-space-data.json',
)
const TEMP_OUTPUT_DIRECTORY = path.join(MOCKS_DIRECTORY, '.cache/contentful-types')
const GENERATED_DEFINITION_PATH = path.join(MOCKS_DIRECTORY, 'src', GENERATED_FILENAME)
const CONTENTFUL_V10_FLAG = '-X'
const RESPONSE_TYPES_FLAG = '-r'

function ensureSpaceExportExists(): void {
  if (!existsSync(SPACE_EXPORT_PATH)) {
    throw new Error(
      `Missing Contentful space export at ${SPACE_EXPORT_PATH}. Run "pnpm --dir lib/mocks fetch:ctfl:space" first.`,
    )
  }
}

function generateRawTypes(): void {
  rmSync(TEMP_OUTPUT_DIRECTORY, { force: true, recursive: true })
  mkdirSync(TEMP_OUTPUT_DIRECTORY, { recursive: true })

  execFileSync(
    'pnpm',
    [
      'dlx',
      'cf-content-types-generator',
      SPACE_EXPORT_PATH,
      CONTENTFUL_V10_FLAG,
      RESPONSE_TYPES_FLAG,
      '--out',
      TEMP_OUTPUT_DIRECTORY,
    ],
    {
      cwd: MOCKS_DIRECTORY,
      stdio: 'inherit',
    },
  )
}

function getGeneratedTypeFiles(): readonly string[] {
  const entries = readdirSync(TEMP_OUTPUT_DIRECTORY)
    .filter((entry) => entry.endsWith('.ts'))
    .filter((entry) => entry !== 'index.ts')
    .sort((left, right) => left.localeCompare(right))
    .map((entry) => path.join(TEMP_OUTPUT_DIRECTORY, entry))

  if (entries.length === 0) {
    throw new Error(`No type files generated in ${TEMP_OUTPUT_DIRECTORY}`)
  }

  return entries
}

function collectContentfulImports(fileContents: string, imports: Set<string>): void {
  const contentfulImportRegex = /^import type \{([^}]+)\} from "contentful";$/gm
  for (const match of fileContents.matchAll(contentfulImportRegex)) {
    const namedImports = match[1] ?? ''
    for (const candidate of namedImports.split(',')) {
      const importName = candidate.trim()
      if (importName.length > 0) imports.add(importName)
    }
  }
}

function stripImportLines(fileContents: string): string {
  return fileContents
    .split('\n')
    .filter((line) => !line.startsWith('import type '))
    .join('\n')
    .trim()
}

function buildCombinedDefinition(generatedTypeFiles: readonly string[]): string {
  const contentfulImports = new Set<string>()
  const sections: string[] = []

  for (const filePath of generatedTypeFiles) {
    const fileContents = readFileSync(filePath, 'utf8')
    collectContentfulImports(fileContents, contentfulImports)
    sections.push(stripImportLines(fileContents))
  }

  const importList = [...contentfulImports].sort((left, right) => left.localeCompare(right))
  if (importList.length === 0) {
    throw new Error('No Contentful type imports found in generated output')
  }

  return (
    '// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.\n\n' +
    `import type { ${importList.join(', ')} } from 'contentful'\n\n` +
    sections.join('\n\n')
  )
}

function main(): void {
  ensureSpaceExportExists()
  generateRawTypes()

  try {
    const generatedTypeFiles = getGeneratedTypeFiles()
    const combinedDefinition = buildCombinedDefinition(generatedTypeFiles)
    writeFileSync(GENERATED_DEFINITION_PATH, `${combinedDefinition}\n`)
    console.info(`Generated ${path.relative(MOCKS_DIRECTORY, GENERATED_DEFINITION_PATH)}`)
  } finally {
    rmSync(TEMP_OUTPUT_DIRECTORY, { force: true, recursive: true })
  }
}

try {
  main()
} catch (error: unknown) {
  const message = error instanceof Error ? (error.stack ?? error.message) : String(error)
  console.error(message)
  process.exit(1)
}
