sharedWorkspaceLockfile: false

overrides:
  '@contentful/optimization-api-client': 'file:../../pkgs/contentful-optimization-api-client-local.tgz'
  '@contentful/optimization-api-schemas': 'file:../../pkgs/contentful-optimization-api-schemas-local.tgz'
  '@contentful/optimization-core': 'file:../../pkgs/contentful-optimization-core-local.tgz'
  '@contentful/optimization-node': 'file:../../pkgs/contentful-optimization-node-local.tgz'
