/* eslint-disable */
// @ts-ignore — generated by `pnpm generate:env`, see src/environments/environment.ts
import { environment as env } from '../environments/environment'

export const environment: Record<string, string> = env
