import { parse } from 'dotenv'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const example = parse(readFileSync('.env.example'))
const actual = existsSync('.env') ? parse(readFileSync('.env')) : {}

const entries = Object.keys(example)
  .map((k) => `  ${k}: ${JSON.stringify(actual[k] ?? example[k] ?? '')}`)
  .join(',\n')

const content = [
  '// Generated by scripts/generate-env.ts — do not edit manually',
  'export const environment = {',
  entries,
  '}',
  '',
].join('\n')

mkdirSync('src/environments', { recursive: true })
writeFileSync('src/environments/environment.ts', content)
