import { parse } from 'dotenv'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const env = parse(readFileSync('.env'))

const entries = Object.keys(env)
  .map((k) => `  ${k}: ${JSON.stringify(env[k])}`)
  .join(',\n')

const content = [
  '// Generated by scripts/generate-env.ts — do not edit manually',
  'export const environment = {',
  entries,
  '}',
  '',
].join('\n')

mkdirSync('src/environments', { recursive: true })
writeFileSync('src/environments/environment.ts', content)
