import { parse } from 'dotenv'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'

const ENV_FILE = '.env'
const EXAMPLE_ENV_FILE = '.env.example'

const envFile = existsSync(ENV_FILE) ? ENV_FILE : EXAMPLE_ENV_FILE
const env = parse(readFileSync(envFile))

const toSingleQuotedString = (value: string | undefined): string =>
  `'${(value ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n')}'`

const entries = Object.keys(env)
  .map((k) => `  ${k}: ${toSingleQuotedString(env[k])},`)
  .join('\n')

const content = [
  '// Generated by scripts/generate-env.ts — do not edit manually',
  'export const environment = {',
  entries,
  '}',
  '',
].join('\n')

mkdirSync('src/environments', { recursive: true })
writeFileSync('src/environments/environment.ts', content)
