package com.contentful.optimization.shared

import com.contentful.java.cda.CDAClient
import okhttp3.Interceptor
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Response
import okhttp3.ResponseBody.Companion.toResponseBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/**
 * The demo app's Contentful Delivery API client, shared by every CDA read (home-screen entries in
 * [ContentfulFetcher] and the preview panel's audience/experience fetch in
 * [MockPreviewContentfulClient]).
 *
 * A production app builds `CDAClient.builder().setSpace(...).setToken(...).build()` against the
 * default `https://cdn.contentful.com/` endpoint and needs none of the properties set here beyond
 * space, environment, and token:
 * - `setEndpoint(AppConfig.contentfulBaseUrl)` points the client at the mock server instead of the
 *   Contentful CDN. Retrofit resolves every `CDAService` path (`spaces/{space}/...`) as relative to
 *   this endpoint, and the mock namespaces the CDA under `/contentful/` (see
 *   `AppConfig.contentfulBaseUrl`), so no path-rewriting shim is needed the way iOS's
 *   `MockContentfulTransport` requires for `contentful.swift`.
 * - `setToken(...)` is required by `CDAClient.Builder` whenever no custom call factory is supplied,
 *   even though the mock server ignores the `Authorization` header entirely.
 * - `setCallFactory(...)` supplies generous timeouts so the first fetch after activity launch stays
 *   deterministic on a loaded CI emulator, and installs [LocalesInterceptor] (see its doc comment
 *   for why that one IS needed, unlike the path-prefix shim above).
 */
object MockContentfulClient {

    private const val MOCK_ACCESS_TOKEN = "mock-access-token"

    val shared: CDAClient by lazy {
        val httpClient = OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .callTimeout(45, TimeUnit.SECONDS)
            .addInterceptor(LocalesInterceptor)
            .build()

        CDAClient.builder()
            .setSpace(AppConfig.contentfulSpaceId)
            .setEnvironment(AppConfig.environment)
            .setToken(MOCK_ACCESS_TOKEN)
            .setEndpoint(AppConfig.contentfulBaseUrl)
            .setCallFactory(httpClient)
            .build()
    }
}

/**
 * Synthesizes the CDA `/locales` and `/content_types` responses contentful.java fetches before its
 * first entry request.
 *
 * Unlike the mock's `/contentful/` path prefix (handled by `setEndpoint`, no shim needed),
 * `CDAClient` unconditionally calls `spaces/{space}/environments/{environment}/locales` and
 * `spaces/{space}/environments/{environment}/content_types` as part of every
 * `fetch(...).all()`/`.one(...)` pipeline and fails to build the array it returns when either call
 * 404s — the mock server serves only `.../entries`. This mirrors iOS's
 * `MockContentfulTransport.serveLocales`: demo-only plumbing a production app against
 * `cdn.contentful.com` needs none of, since the real CDA always serves both routes.
 *
 * Every synthetic array item must include a `sys.type`, matching the real CDA response shape:
 * `CDAArray.items` is generically typed `List<CDAResource>`, so contentful.java's
 * `ResourceDeserializer` runs over every item in *any* array response (including these) and throws
 * a `NullPointerException` reading a missing `sys` object.
 *
 * Content types can't resolve to an empty array: `RichTextFactory.resolveRichTextField` looks up
 * every fetched entry's content type by ID (`ResourceUtils.ensureContentType`) to know which fields
 * are Rich Text, and throws `CDAContentTypeNotFoundException` when it isn't found — so
 * [ContentTypesFixture] bundles the app's real, exported content-type definitions
 * (`contentful/content_types.json`, generated by `lib/mocks`' `fetch:ctfl:space`) and serves them
 * verbatim.
 */
private object LocalesInterceptor : Interceptor {

    private val SYNTHESIZED_SEGMENTS = setOf("locales", "content_types")

    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()
        val segment = request.url.pathSegments.lastOrNull()
        if (segment !in SYNTHESIZED_SEGMENTS) return chain.proceed(request)

        val responseJson = if (segment == "locales") localesResponseJson() else ContentTypesFixture.json

        return Response.Builder()
            .request(request)
            .protocol(chain.connection()?.protocol() ?: okhttp3.Protocol.HTTP_1_1)
            .code(200)
            .message("OK")
            .body(responseJson.toResponseBody("application/json".toMediaType()))
            .build()
    }

    private fun localesResponseJson(): String {
        val locale = JSONObject().apply {
            put("sys", JSONObject().put("type", "Locale"))
            put("name", "English (United States)")
            put("code", AppConfig.defaultContentfulLocale)
            put("fallbackCode", JSONObject.NULL)
            put("default", true)
            put("contentDeliveryApi", true)
            put("contentManagementApi", true)
            put("optional", false)
        }
        val body = JSONObject().apply {
            put("sys", JSONObject().put("type", "Array"))
            put("total", 1)
            put("skip", 0)
            put("limit", 1000)
            put("items", JSONArray().put(locale))
        }
        return body.toString()
    }
}

/**
 * The Contentful space's real content-type definitions, exported via `lib/mocks`' `fetch:ctfl:space`
 * script and bundled verbatim from `lib/mocks/src/contentful/data/space/ctfl-space-data.json`'s
 * `contentTypes` array. Loaded once from the classpath resource `contentful/content_types.json`,
 * which every Android build packages from `src/main/resources`.
 */
private object ContentTypesFixture {

    val json: String by lazy {
        val stream = requireNotNull(
            javaClass.classLoader?.getResourceAsStream("contentful/content_types.json"),
        ) { "Missing bundled resource contentful/content_types.json" }
        stream.bufferedReader().use { it.readText() }
    }
}
