// Default values — overwritten at build time by scripts/generate-env.ts
export const environment: Record<string, string | undefined> = {
  PUBLIC_NINETAILED_CLIENT_ID: '',
  PUBLIC_NINETAILED_ENVIRONMENT: '',
  PUBLIC_INSIGHTS_API_BASE_URL: '',
  PUBLIC_EXPERIENCE_API_BASE_URL: '',
  PUBLIC_CONTENTFUL_TOKEN: '',
  PUBLIC_CONTENTFUL_ENVIRONMENT: '',
  PUBLIC_CONTENTFUL_SPACE_ID: '',
  PUBLIC_CONTENTFUL_CDA_HOST: '',
  PUBLIC_CONTENTFUL_BASE_PATH: '',
  PUBLIC_OPTIMIZATION_ENABLE_PREVIEW_PANEL: '',
  PUBLIC_OPTIMIZATION_LOG_LEVEL: '',
}
