sharedWorkspaceLockfile: false

allowBuilds:
  sharp: false
  unrs-resolver: false

overrides:
  '@contentful/optimization-api-client': 'file:../../pkgs/contentful-optimization-api-client-local.tgz'
  '@contentful/optimization-api-schemas': 'file:../../pkgs/contentful-optimization-api-schemas-local.tgz'
  '@contentful/optimization-core': 'file:../../pkgs/contentful-optimization-core-local.tgz'
  '@contentful/optimization-node': 'file:../../pkgs/contentful-optimization-node-local.tgz'
  '@contentful/optimization-nextjs': 'file:../../pkgs/contentful-optimization-nextjs-local.tgz'
  '@contentful/optimization-web': 'file:../../pkgs/contentful-optimization-web-local.tgz'
  '@contentful/optimization-react-web': 'file:../../pkgs/contentful-optimization-react-web-local.tgz'
  '@contentful/optimization-web-preview-panel': 'file:../../pkgs/contentful-optimization-web-preview-panel-local.tgz'
