#!/bin/bash

# Don't run cz if a message has been supplied
[ "$2" = "message" ] && exit 0

# Don't run cz if we're amending the previous commit
[ "$2" = "commit" ] && [ "$3" = "HEAD" ] && exit 0

if [[ $COMMIT_MSG =~ ^$ ]]; then
  exec </dev/tty && node_modules/.bin/cz --hook || true
fi
